# Change the port to avoid the conflict you saw in the last run
server.port=8081

spring.application.name=backend
spring.data.mongodb.uri=mongodb://localhost:27017/nextstop_db
spring.data.mongodb.database=nextstop_db